#index:
#    path: /
#    controller: App\Controller\DefaultController::index

// associate controller function with a public URL 
app_beer_articles:
    path: /articles
    controller: App\Controller\ArticleController::number